/**
 * Canonical PostgreSQL schema (T014).
 *
 * Kept in one module so cross-table references (deferred circular foreign
 * keys between items and revisions are added in reviewed SQL migrations)
 * stay easy to audit. Column-level invariants live here; graph-level
 * invariants (cycles, final-placement transitions) are enforced by domain
 * services plus recursive queries inside one transaction.
 */

import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  customType,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { definePageOperationSchema } from "./page-operations.ts";
import { authorizedDevices, protectedEnvelopes } from "./security/index.ts";

const bytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType() {
    return "bytea";
  },
});

export const workspaces = pgTable(
  "workspaces",
  {
    id: uuid("id").primaryKey(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    schemaVersion: integer("schema_version").notNull(),
  },
  (table) => [
    // Exactly one canonical workspace per installation (FR-001): a unique
    // index on a constant expression admits at most one row, so a concurrent
    // second bootstrap fails loudly instead of inserting a stray workspace.
    // Added in migration 0002_workspace_singleton.sql.
    uniqueIndex("workspaces_singleton_idx").on(sql`(true)`),
    check("workspaces_schema_version_check", sql`${table.schemaVersion} >= 1`),
  ],
);

export const items = pgTable(
  "items",
  {
    id: uuid("id").primaryKey(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    kind: text("kind").notNull(),
    name: text("name").notNull(),
    lifecycle: text("lifecycle").notNull().default("active"),
    trashedAt: timestamp("trashed_at", { withTimezone: true }),
    purgeAfter: timestamp("purge_after", { withTimezone: true }),
    // FK to revisions(id) is added as DEFERRABLE INITIALLY DEFERRED in SQL,
    // so the item row and its creation revision commit atomically.
    currentRevisionId: uuid("current_revision_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    /** Per-installation, not per-device: one owner, one answer (FR-012). */
    favourite: boolean("favourite").notNull().default(false),
    /**
     * The owner asked for this to be kept on their devices (feature 005,
     * FR-016). Like `favourite`, it is what the owner wants rather than what a
     * device happens to hold; whether a given device has fetched the content is
     * per-device and lives in the local projection.
     */
    offlineIntent: boolean("offline_intent").notNull().default(false),
    // Generated by the database from `kind`; never written by the application.
    // Declared here so the composite key below can reference it.
    isFile: boolean("is_file").generatedAlwaysAs(sql`kind = 'file'`),
  },
  (table) => [
    // Keyed on (id, is_file), not (id, kind). `kind` is mutable between 'page'
    // and 'folder' since feature 004, and a placement must not break when it
    // changes — see specs/004-unified-items-conversion/research.md, decision 1.
    uniqueIndex("items_id_is_file_unique").on(table.id, table.isFile),
    uniqueIndex("items_id_workspace_unique").on(table.id, table.workspaceId),
    index("items_workspace_lifecycle_idx").on(table.workspaceId, table.lifecycle),
    check("items_kind_check", sql`${table.kind} IN ('page', 'folder', 'file')`),
    check("items_lifecycle_check", sql`${table.lifecycle} IN ('active', 'trashed', 'purged')`),
    check("items_name_check", sql`length(${table.name}) BETWEEN 1 AND 512`),
    check(
      "items_trash_metadata_check",
      sql`(${table.lifecycle} <> 'trashed') OR (${table.trashedAt} IS NOT NULL AND ${table.purgeAfter} IS NOT NULL)`,
    ),
  ],
);

export const placements = pgTable(
  "placements",
  {
    id: uuid("id").primaryKey(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    itemId: uuid("item_id").notNull(),
    // Denormalised from `items.is_file`, not from `items.kind`.
    //
    // Both constraints that read it only ask whether the item is a file: an
    // attachment must be one, and a non-file has exactly one hierarchy
    // placement. Neither ever distinguished a page from a folder, so copying
    // the whole kind denormalised a mutable value to enforce a rule about an
    // immutable one — which is what made conversion impossible.
    itemIsFile: boolean("item_is_file").notNull(),
    kind: text("kind").notNull(),
    parentItemId: uuid("parent_item_id"),
    positionKey: text("position_key").notNull(),
    removedAt: timestamp("removed_at", { withTimezone: true }),
    createdRevisionId: uuid("created_revision_id").notNull(),
    removedRevisionId: uuid("removed_revision_id"),
  },
  (table) => [
    index("placements_parent_active_idx").on(table.parentItemId, table.kind),
    index("placements_item_idx").on(table.itemId),
    // Pages and folders: exactly one active hierarchy placement.
    uniqueIndex("placements_single_hierarchy_unique")
      .on(table.itemId)
      .where(
        sql`${table.kind} = 'hierarchy' AND ${table.removedAt} IS NULL AND NOT ${table.itemIsFile}`,
      ),
    check("placements_kind_check", sql`${table.kind} IN ('hierarchy', 'attachment')`),
    check(
      "placements_attachment_parent_check",
      sql`(${table.kind} <> 'attachment') OR (${table.parentItemId} IS NOT NULL)`,
    ),
    check(
      "placements_attachment_file_check",
      sql`(${table.kind} <> 'attachment') OR ${table.itemIsFile}`,
    ),
    check("placements_position_key_check", sql`length(${table.positionKey}) BETWEEN 1 AND 255`),
  ],
);

export const pageDocuments = pgTable(
  "page_documents",
  {
    pageId: uuid("page_id")
      .primaryKey()
      .references(() => items.id),
    format: text("format").notNull(),
    formatVersion: integer("format_version").notNull(),
    body: jsonb("body").notNull(),
  },
  (table) => [
    check("page_documents_format_check", sql`${table.format} = 'myownnotion.document+json'`),
    check("page_documents_version_check", sql`${table.formatVersion} >= 1`),
  ],
);

export const fileContents = pgTable(
  "file_contents",
  {
    id: uuid("id").primaryKey(),
    sha256: bytea("sha256").notNull(),
    byteLength: bigint("byte_length", { mode: "number" }).notNull(),
    storageKey: text("storage_key").notNull().unique(),
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    referenceCount: integer("reference_count").notNull().default(0),
  },
  (table) => [
    index("file_contents_digest_idx").on(table.sha256, table.byteLength),
    check("file_contents_length_check", sql`${table.byteLength} >= 0`),
    check("file_contents_sha256_check", sql`octet_length(${table.sha256}) = 32`),
  ],
);

export const logicalFiles = pgTable(
  "logical_files",
  {
    itemId: uuid("item_id")
      .primaryKey()
      .references(() => items.id),
    contentId: uuid("content_id")
      .notNull()
      .references(() => fileContents.id),
    mediaType: text("media_type").notNull(),
    originalName: text("original_name").notNull(),
    byteLength: bigint("byte_length", { mode: "number" }).notNull(),
  },
  (table) => [check("logical_files_length_check", sql`${table.byteLength} >= 0`)],
);

/**
 * Where a file is used (feature 005, FR-004, FR-005).
 *
 * Derived from placements and from the embeds inside page documents, never
 * maintained by hand. An incomplete index here is worse than none: it produces
 * a deletion confirmation claiming a file is unused when it is not, and the
 * owner then destroys something they still need.
 *
 * `file_contents.reference_count` above answers "is this used at all" and is
 * kept for reclaiming storage. It cannot name a usage, which is the whole
 * question a confirmation has to answer.
 */
export const fileUsages = pgTable(
  "file_usages",
  {
    fileItemId: uuid("file_item_id")
      .notNull()
      .references(() => items.id, { onDelete: "cascade" }),
    usedByItemId: uuid("used_by_item_id")
      .notNull()
      .references(() => items.id, { onDelete: "cascade" }),
    usageKind: text("usage_kind").notNull(),
    /** Which block embeds it; null for the placement kinds. */
    blockId: uuid("block_id"),
  },
  (table) => [
    index("file_usages_by_file_idx").on(table.fileItemId),
    index("file_usages_by_user_idx").on(table.usedByItemId),
    check(
      "file_usages_kind_check",
      sql`${table.usageKind} IN ('attachment', 'embed', 'hierarchy')`,
    ),
    check(
      "file_usages_block_check",
      sql`(${table.usageKind} = 'embed') = (${table.blockId} IS NOT NULL)`,
    ),
  ],
);

/**
 * A transfer that has not finished yet (feature 005, FR-006).
 *
 * What matters most is what this table does *not* reference: there is no item
 * and no placement until the bytes are complete and verified, so a partial
 * upload cannot appear anywhere as a file. That is a property of the shape
 * rather than a check someone has to remember to write.
 */
export const uploads = pgTable(
  "uploads",
  {
    id: uuid("id").primaryKey(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    declaredLength: bigint("declared_length", { mode: "number" }).notNull(),
    /**
     * The authoritative offset, and the only one. A client that believes it
     * sent more than this is wrong by definition — which is why the protocol
     * has the client ask rather than assume.
     */
    receivedLength: bigint("received_length", { mode: "number" }).notNull().default(0),
    mediaType: text("media_type").notNull(),
    originalName: text("original_name").notNull(),
    /**
     * Editor uploads finalize as attachments of this page. Deliberately not a
     * foreign key: deleting a page while bytes are in flight must not mutate
     * the transfer record; finalization will refuse the now-invalid placement.
     */
    attachmentParentItemId: uuid("attachment_parent_item_id"),
    storageKey: text("storage_key").notNull().unique(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    /** Abandoned uploads are reclaimed; otherwise they occupy storage nothing accounts for. */
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  },
  (table) => [
    index("uploads_expiry_idx").on(table.expiresAt),
    check("uploads_declared_length_check", sql`${table.declaredLength} >= 0`),
    check(
      "uploads_received_length_check",
      sql`${table.receivedLength} >= 0 AND ${table.receivedLength} <= ${table.declaredLength}`,
    ),
  ],
);

export const mutations = pgTable(
  "mutations",
  {
    id: uuid("id").primaryKey(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    commandType: text("command_type").notNull(),
    status: text("status").notNull(),
    submittedAt: timestamp("submitted_at", { withTimezone: true }).notNull().defaultNow(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    resultRevisionIds: uuid("result_revision_ids").array().notNull().default([]),
    failureCode: text("failure_code"),
    // Competing revision identities of a rejected concurrent mutation, so a
    // replay returns the same information as the first response (FR-042).
    // Added in migration 0003_mutation_competing_revisions.sql.
    competingRevisionIds: uuid("competing_revision_ids").array().notNull().default([]),
  },
  (table) => [
    check("mutations_status_check", sql`${table.status} IN ('accepted', 'rejected')`),
    check(
      "mutations_competing_only_when_rejected",
      sql`${table.status} = 'rejected' OR cardinality(${table.competingRevisionIds}) = 0`,
    ),
    check(
      "mutations_result_check",
      sql`(${table.status} <> 'accepted') OR (cardinality(${table.resultRevisionIds}) >= 1)`,
    ),
  ],
);

export const revisions = pgTable(
  "revisions",
  {
    id: uuid("id").primaryKey(),
    itemId: uuid("item_id")
      .notNull()
      .references(() => items.id),
    mutationId: uuid("mutation_id")
      .notNull()
      .references(() => mutations.id),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }).notNull().defaultNow(),
    /**
     * Which device wrote this (feature 006, FR-022).
     *
     * Nullable because revisions written before this feature have no device to
     * name, and a default would put a false statement in a history the owner
     * reads. "Device unknown" is honest; a guess is worse than silence.
     */
    authoredByDeviceId: uuid("authored_by_device_id"),
    snapshot: jsonb("snapshot"),
    snapshotExpiresAt: timestamp("snapshot_expires_at", { withTimezone: true }),
    lineageDigest: text("lineage_digest").notNull(),
  },
  (table) => [index("revisions_item_idx").on(table.itemId)],
);

/**
 * A structured database is a capability attached to a canonical page.
 * Labels, properties, views and values are deliberately absent: those private
 * payloads live in protected records keyed by the structural versions here.
 */
export const databases = pgTable(
  "databases",
  {
    itemId: uuid("item_id")
      .primaryKey()
      .references(() => items.id),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    definitionVersion: integer("definition_version").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("databases_item_workspace_unique").on(table.itemId, table.workspaceId),
    index("databases_workspace_idx").on(table.workspaceId),
    foreignKey({
      name: "databases_item_workspace_fk",
      columns: [table.itemId, table.workspaceId],
      foreignColumns: [items.id, items.workspaceId],
    }),
    check("databases_definition_version_check", sql`${table.definitionVersion} >= 1`),
  ],
);

/** One active database membership per canonical entry page. */
export const databaseEntries = pgTable(
  "database_entries",
  {
    entryItemId: uuid("entry_item_id")
      .primaryKey()
      .references(() => items.id),
    databaseId: uuid("database_id")
      .notNull()
      .references(() => databases.itemId),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    valueVersion: integer("value_version").notNull(),
    addedRevisionId: uuid("added_revision_id")
      .notNull()
      .references(() => revisions.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("database_entries_database_idx").on(table.databaseId),
    index("database_entries_workspace_idx").on(table.workspaceId),
    foreignKey({
      name: "database_entries_item_workspace_fk",
      columns: [table.entryItemId, table.workspaceId],
      foreignColumns: [items.id, items.workspaceId],
    }),
    foreignKey({
      name: "database_entries_database_workspace_fk",
      columns: [table.databaseId, table.workspaceId],
      foreignColumns: [databases.itemId, databases.workspaceId],
    }),
    check("database_entries_not_self_check", sql`${table.entryItemId} <> ${table.databaseId}`),
    check("database_entries_value_version_check", sql`${table.valueVersion} >= 1`),
  ],
);

export const revisionParents = pgTable(
  "revision_parents",
  {
    revisionId: uuid("revision_id")
      .notNull()
      .references(() => revisions.id),
    parentRevisionId: uuid("parent_revision_id")
      .notNull()
      .references(() => revisions.id),
  },
  (table) => [
    primaryKey({ columns: [table.revisionId, table.parentRevisionId] }),
    index("revision_parents_parent_idx").on(table.parentRevisionId),
  ],
);

export { changes } from "./change-sequence.ts";
// Owner security foundation tables (feature 002). Kept in their own module so
// the canonical content schema above stays readable and untouched.
export * from "./security/index.ts";

export const relationships = pgTable(
  "relationships",
  {
    id: uuid("id").primaryKey(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    sourceItemId: uuid("source_item_id")
      .notNull()
      .references(() => items.id),
    targetItemId: uuid("target_item_id")
      .notNull()
      .references(() => items.id),
    relationType: text("relation_type").notNull(),
    metadata: jsonb("metadata").notNull().default({}),
    createdRevisionId: uuid("created_revision_id")
      .notNull()
      .references(() => revisions.id),
    removedRevisionId: uuid("removed_revision_id").references(() => revisions.id),
  },
  (table) => [
    index("relationships_source_idx").on(table.sourceItemId),
    index("relationships_target_idx").on(table.targetItemId),
    check(
      "relationships_type_check",
      sql`${table.relationType} ~ '^[a-z][a-z0-9.-]*:[a-z][a-z0-9.-]*$'`,
    ),
  ],
);

export const lifecycleEvents = pgTable(
  "lifecycle_events",
  {
    id: uuid("id").primaryKey(),
    itemId: uuid("item_id")
      .notNull()
      .references(() => items.id),
    mutationId: uuid("mutation_id")
      .notNull()
      .references(() => mutations.id),
    eventType: text("event_type").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
    placementSnapshot: jsonb("placement_snapshot").notNull().default([]),
  },
  (table) => [
    index("lifecycle_events_item_idx").on(table.itemId),
    check(
      "lifecycle_events_type_check",
      sql`${table.eventType} IN ('trashed', 'restored', 'purged')`,
    ),
  ],
);

export const exports = pgTable(
  "exports",
  {
    id: uuid("id").primaryKey(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    status: text("status").notNull().default("pending"),
    digest: text("digest"),
    manifest: jsonb("manifest"),
    problem: jsonb("problem"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    ready: boolean("ready").notNull().default(false),
  },
  (table) => [
    check("exports_status_check", sql`${table.status} IN ('pending', 'ready', 'failed')`),
  ],
);

/**
 * Backups, their verifications, and restoration attempts (feature 007).
 *
 * Three tables rather than one. The split that matters is the second: a backup
 * is verified after creation *and* again after transfer, and those are different
 * facts with different failure modes — an archive can be sound on disk and
 * corrupt at the destination.
 */
export const backups = pgTable(
  "backups",
  {
    id: uuid("id").primaryKey(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    /**
     * The change-feed position this archive represents.
     *
     * Consistency is not a separate mechanism here: the product already orders
     * every change, so "one moment" is a number it already has. It also makes a
     * restored workspace placeable — an owner can say what they lost in changes
     * rather than in minutes.
     */
    cursor: text("cursor").notNull(),
    applicationVersion: text("application_version").notNull(),
    schemaVersion: integer("schema_version").notNull(),
    recordFormatVersion: integer("record_format_version").notNull(),
    byteLength: bigint("byte_length", { mode: "number" }).notNull(),
    digest: text("digest").notNull(),
    /**
     * Null while the archive exists only locally.
     *
     * A backup produced and not yet transferred is a real state, and one that
     * must not be read as a failure — retention depends on telling them apart.
     */
    destination: text("destination"),
    remoteName: text("remote_name"),
    reason: text("reason").notNull().default("scheduled"),
    /** For a pre-update backup: the version being moved to. */
    supersededByVersion: text("superseded_by_version"),
  },
  (table) => [
    check("backups_reason_check", sql`${table.reason} IN ('scheduled', 'manual', 'pre-update')`),
    check(
      "backups_remote_pair_check",
      sql`(${table.destination} IS NULL) = (${table.remoteName} IS NULL)`,
    ),
    index("backups_created_idx").on(table.workspaceId, table.createdAt),
  ],
);

/**
 * One row per check performed against a backup.
 *
 * Rows rather than columns, and this is what the table exists to make possible:
 * a verification is an event that happened at a time, and a backup can be
 * checked again later — after a destination outage, or because the owner asked.
 * Columns would keep only the last answer and would silently overwrite the
 * history of a backup that passed and then failed.
 */
export const backupVerifications = pgTable(
  "backup_verifications",
  {
    id: uuid("id").primaryKey(),
    backupId: uuid("backup_id")
      .notNull()
      .references(() => backups.id, { onDelete: "cascade" }),
    stage: text("stage").notNull(),
    checkedAt: timestamp("checked_at", { withTimezone: true }).notNull().defaultNow(),
    outcome: text("outcome").notNull(),
    /** A safe reason. Never a path, a credential, or anything from the archive. */
    detail: text("detail"),
  },
  (table) => [
    check(
      "backup_verifications_stage_check",
      sql`${table.stage} IN ('after-creation', 'after-transfer')`,
    ),
    check("backup_verifications_outcome_check", sql`${table.outcome} IN ('passed', 'failed')`),
    index("backup_verifications_passed_idx").on(table.backupId, table.stage, table.checkedAt),
  ],
);

export const restorationAttempts = pgTable(
  "restoration_attempts",
  {
    id: uuid("id").primaryKey(),
    backupId: uuid("backup_id")
      .notNull()
      .references(() => backups.id),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    /**
     * Null while running.
     *
     * A row left null by a process that is no longer alive *is* the interrupted
     * state FR-017 is about. The installation reads it at startup and refuses to
     * present itself as healthy, rather than inferring health from the absence
     * of an error.
     */
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    kind: text("kind").notNull(),
    outcome: text("outcome"),
    detail: text("detail"),
    restoredItemCount: integer("restored_item_count"),
  },
  (table) => [
    check("restoration_attempts_kind_check", sql`${table.kind} IN ('test', 'destructive')`),
    check(
      "restoration_attempts_outcome_check",
      sql`${table.outcome} IS NULL OR ${table.outcome} IN ('succeeded', 'failed')`,
    ),
    check(
      "restoration_attempts_finished_check",
      sql`(${table.finishedAt} IS NULL) = (${table.outcome} IS NULL)`,
    ),
    index("restoration_attempts_started_idx").on(table.startedAt),
  ],
);

export const {
  pageOperationStates,
  pageOperationUpdates,
  pageOperationCheckpoints,
  pageDeviceFrontiers,
  pageAmbiguities,
  pageLegacyBranchConversions,
} = definePageOperationSchema({
  workspaceId: workspaces.id,
  itemId: items.id,
  itemWorkspaceId: items.workspaceId,
  revisionId: revisions.id,
  backupId: backups.id,
  deviceId: authorizedDevices.id,
  protectedEnvelopeId: protectedEnvelopes.id,
});
