/**
 * Catalogue français de la fonctionnalité bases de données.
 *
 * Les libellés restent séparés des valeurs canoniques afin qu'une traduction
 * ne modifie jamais les données enregistrées ni le protocole de synchronisation.
 */
export const DATABASE_COPY = {
  common: {
    cancel: "Annuler",
    close: "Fermer",
    conflict: "Conflit",
    remove: "Supprimer",
    savedLocally: "Enregistré localement",
    saving: "Enregistrement…",
    savingLocally: "Enregistrement local…",
    unavailableOption: "Option indisponible",
    unavailableProperty: "Propriété indisponible",
    noUsableView: "Cette base de données ne contient aucune vue utilisable.",
    noEntriesAvailable: "Aucune entrée dans les données disponibles sur cet appareil.",
    noEntries: "Aucune entrée dans cette vue.",
    noCardsAvailable: "Aucune carte dans les données disponibles sur cet appareil.",
    noCards: "Aucune carte dans cette vue.",
    noValue: "Aucune valeur",
    noPage: "Aucune page",
    preserveIncompatible: "Conserver les valeurs incompatibles",
    discardAffected: "Supprimer les valeurs concernées",
  },
  create: {
    nameRequired: "Donnez un nom à la base de données.",
    failed: "La base de données n'a pas pu être créée. Le nom saisi est conservé.",
    label: "Créer une base de données",
    placeholder: "Projets, tâches, lectures…",
    creating: "Création…",
    submit: "Créer la base de données",
    initialViewName: "Tableau",
    initialTitlePropertyName: "Titre",
  },
  page: {
    propertySaveFailed: "La propriété n'a pas pu être enregistrée. Le brouillon est conservé.",
    titleRequired: "Donnez un titre à la page.",
    entryCreateFailed: "L'entrée n'a pas pu être créée. Le titre saisi est conservé.",
    eyebrow: "Base de données · page",
    contents: "Contenu de la base de données",
    addProperty: "Ajouter une propriété",
    properties: "Propriétés",
    confirmSchemaChange: "Confirmer la modification de structure",
    schemaImpactHeading: "Cette modification affecte des valeurs enregistrées",
    newEntry: "Nouvelle entrée",
    untitledPage: "Sans titre",
    loadingView: "Chargement de la vue enregistrée…",
    invalidView: "Cette vue est invalide. Corrigez la règle signalée.",
    rebuildingView:
      "La vue complète est en cours de reconstruction. Les données locales sûres restent visibles.",
    staleView: "La vue a changé ; la première page a été rechargée.",
    impact: (valueCount: number, entryCount: number) =>
      `${valueCount} ${valueCount === 1 ? "valeur" : "valeurs"} dans ${entryCount} ${entryCount === 1 ? "entrée" : "entrées"}.`,
    completeResult: (count: number) =>
      `Résultat complet · ${count} ${count === 1 ? "entrée" : "entrées"}`,
    partialResult: (available: number, expected: number) =>
      `Données locales partielles : ${available} sur ${expected}`,
  },
  toolbar: {
    viewName: "Nom de la vue",
    renaming: "Renommage…",
    rename: "Renommer la vue",
    savedViews: "Vues enregistrées de la base de données",
    views: "Vues",
    viewTypes: {
      table: "tableau",
      list: "liste",
      board: "tableau Kanban",
      gallery: "galerie",
      calendar: "calendrier",
    },
    newTable: "Nouvelle vue tableau",
    newList: "Nouvelle vue liste",
    newBoard: "Nouvelle vue Kanban",
    newGallery: "Nouvelle vue galerie",
    newCalendar: "Nouvelle vue calendrier",
    boardNeedsProperty: "Ajoutez d'abord une propriété de statut ou de sélection",
    calendarNeedsProperty: "Ajoutez d'abord une propriété de date",
    duplicate: "Dupliquer la vue",
    moveEarlier: "Déplacer la vue vers la gauche",
    moveLater: "Déplacer la vue vers la droite",
    remove: "Supprimer la vue",
    needsOneView: "Une base de données doit conserver au moins une vue active",
    visibleProperties: "Propriétés visibles",
    defaultViewName: (type: "table" | "list" | "board" | "gallery" | "calendar", n: number) =>
      `${
        {
          table: "Tableau",
          list: "Liste",
          board: "Kanban",
          gallery: "Galerie",
          calendar: "Calendrier",
        }[type]
      } ${n}`,
    copyName: (name: string) => `${name} — copie`,
    actionsFor: (name: string) => `Actions pour ${name}`,
    moveColumnEarlier: (name: string) => `Déplacer la colonne ${name} vers la gauche`,
    moveColumnLater: (name: string) => `Déplacer la colonne ${name} vers la droite`,
  },
  property: {
    nameRequired: "Donnez un nom à la propriété.",
    nameTooLong: "Le nom d'une propriété ne peut pas dépasser 512 caractères.",
    distinctOptions: "Chaque option doit avoir un libellé distinct.",
    editor: "Éditeur de propriété",
    name: "Nom",
    type: "Type",
    typeLabels: {
      title: "titre",
      text: "texte",
      number: "nombre",
      date: "date",
      status: "statut",
      select: "sélection",
      "multi-select": "sélection multiple",
      checkbox: "case à cocher",
      relation: "relation",
    },
    optionPlaceholder: "Prévu, En cours, Terminé",
    optionsSeparated: "Options séparées par des virgules",
    dateMode: "Précision de la date",
    calendarDate: "Date du calendrier",
    dateAndTime: "Date et heure",
    relationCardinality: "Cibles autorisées",
    onePage: "Une page",
    manyPages: "Plusieurs pages",
    save: "Enregistrer la propriété",
  },
  value: {
    titleOnPage: "Le titre se modifie directement dans le nom de la page.",
    chooseChecked: "Indiquez si cette case est cochée.",
    chooseOptions: "Choisissez une ou plusieurs options.",
    staleOption: "Une de ces options n'est plus disponible.",
    choosePage: "Choisissez une page disponible.",
    onePageOnly: "Cette relation n'accepte qu'une seule page.",
    enter: "Saisissez une valeur.",
    decimalDot: "Utilisez un point comme séparateur décimal.",
    decimalExample: "Saisissez un nombre décimal, par exemple 12.5.",
    realDate: "Saisissez une date réelle au format AAAA-MM-JJ.",
    zonedDate: "Saisissez une date et une heure avec un décalage de fuseau horaire.",
    chooseOption: "Choisissez une option disponible.",
    unavailableOption: "Cette option n'est plus disponible.",
    unsupported: "Ce type de valeur n'est pas pris en charge.",
    emptyText: "Texte vide",
    yes: "Oui",
    no: "Non",
    linked: (count: number) => `${count} liée${count === 1 ? "" : "s"}`,
  },
  filter: {
    periodFor: (name: string) => `Période pour ${name}`,
    from: "Du",
    to: "Au",
    fromFor: (name: string, timezone: string) => `Début pour ${name}${timezone}`,
    toFor: (name: string, timezone: string) => `Fin pour ${name}${timezone}`,
    valueFor: (name: string) => `Valeur pour ${name}`,
    chooseOption: "Choisir une option",
    notChecked: "Non cochée",
    checked: "Cochée",
    pageIdentity: "Identité de la page",
    value: "Valeur",
    filters: "Filtres",
    allRulesShort: "toutes les règles",
    anyRuleShort: "au moins une règle",
    match: "Correspondance",
    combination: "Combinaison des filtres",
    allRules: "Toutes les règles",
    anyRules: "Au moins une règle",
    unavailable: "Propriété indisponible · corrigez ou supprimez ce filtre",
    property: "Propriété",
    operator: "Opérateur",
    operatorLabels: {
      equals: "est égal à",
      "not-equals": "est différent de",
      "is-empty": "est vide",
      "is-not-empty": "n'est pas vide",
      contains: "contient",
      "not-contains": "ne contient pas",
      before: "est avant",
      after: "est après",
      between: "est entre",
      "less-than": "est inférieur à",
      "greater-than": "est supérieur à",
    },
    removeRule: "Supprimer la règle",
    add: "Ajouter un filtre",
    clear: "Effacer les filtres",
    saving: "Enregistrement des filtres…",
    save: "Enregistrer les filtres",
  },
  sort: {
    heading: "Tri et regroupement",
    grouped: "regroupé",
    property: "Propriété de tri",
    direction: "Direction",
    ascending: "Croissant",
    descending: "Décroissant",
    emptyValues: "Valeurs vides",
    last: "À la fin",
    first: "Au début",
    remove: "Supprimer le tri",
    moveEarlier: "Remonter le tri",
    moveLater: "Descendre le tri",
    add: "Ajouter un tri",
    groupBy: "Regrouper par",
    noGrouping: "Aucun regroupement",
    saving: "Enregistrement du tri et du regroupement…",
    save: "Enregistrer le tri et le regroupement",
    summary: (count: number, grouped: boolean) =>
      `Tri et regroupement · ${count} ${count === 1 ? "tri" : "tris"}${grouped ? " · regroupé" : ""}`,
  },
  board: {
    noPropertyValue: (name: string) => `Sans ${name.toLocaleLowerCase(DATABASE_LOCALE)}`,
    cardsFor: (name: string) => `Cartes de ${name}`,
    moveToAnother: (title: string) => `Déplacer ${title} dans une autre colonne`,
    movePrevious: (title: string) => `Déplacer ${title} dans la colonne précédente`,
    moveNext: (title: string) => `Déplacer ${title} dans la colonne suivante`,
    previous: "Colonne précédente",
    next: "Colonne suivante",
    viewLabel: (name: string) => `Vue Kanban ${name}`,
    needsProperty:
      "Ajoutez une propriété active de statut ou de sélection pour utiliser cette vue.",
    moved: (title: string, column: string) => `${title} a été déplacé dans ${column}`,
    moveFailed: (title: string) => `${title} n'a pas pu être déplacé`,
    groupingProperty: "Propriété de regroupement du Kanban",
    columnsGroupedBy: (name: string) => `Colonnes regroupées par ${name}`,
    expand: "Déplier",
    collapse: "Replier",
    noCards: "Aucune carte",
  },
  calendar: {
    viewLabel: (name: string) => `Vue calendrier ${name}`,
    needsProperty: "Ajoutez une propriété active de date pour utiliser ce calendrier.",
    scheduled: (title: string, date: string) => `${title} est planifié pour le ${date}`,
    scheduleFailed: (title: string) => `${title} n'a pas pu être planifié`,
    schedule: (title: string) => `Planifier ${title}`,
    movePrevious: (title: string) => `Déplacer ${title} au jour précédent`,
    moveNext: (title: string) => `Déplacer ${title} au jour suivant`,
    previousDay: "Jour précédent",
    nextDay: "Jour suivant",
    dateProperty: "Propriété de date du calendrier",
    previousMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    weekdays: ["lun.", "mar.", "mer.", "jeu.", "ven.", "sam.", "dim."],
    unscheduled: "Non planifiées",
    allScheduled: "Toutes les entrées visibles sont planifiées.",
  },
  gallery: {
    previewDisabled: "Aperçu désactivé",
    noSafePreview: "Aucun aperçu sûr disponible",
    viewLabel: (name: string) => `Vue galerie ${name}`,
    settings: "Réglages des cartes de la galerie",
    preview: "Aperçu de la carte",
    none: "Aucun aperçu",
    page: "Contenu de la page",
    file: "Premier fichier sûr disponible",
    properties: "Propriétés affichées sur les cartes",
  },
  list: {
    viewLabel: (name: string) => `Vue liste ${name}`,
  },
  entry: {
    saved: "Propriétés enregistrées localement.",
    saveFailed:
      "Les propriétés n'ont pas pu être enregistrées. Les valeurs saisies sont conservées.",
    eyebrow: "Entrée de base de données · page",
    close: "Fermer l'entrée",
    noProperties: "Cette base de données ne contient pas encore de propriété supplémentaire.",
    taskTracking: "Suivi des tâches",
    taskStatus: "Statut de la tâche",
    taskDueDate: "Échéance de la tâche",
    taskPriority: "Priorité de la tâche",
    otherProperties: "Autres propriétés",
    save: "Enregistrer les propriétés",
    pageContent: "Contenu de la page",
    samePageDocument: "Le document éditorial appartient à cette même page.",
  },
  task: {
    notConfigured: "Non configuré",
    saveFailed:
      "Les rôles de tâche n'ont pas pu être enregistrés. La configuration précédente a été restaurée.",
    tracking: "Suivi des tâches",
    explanation:
      "Les rôles de tâche utilisent des propriétés existantes. Les entrées restent des pages ordinaires et modifiables.",
    disable: "Désactiver le suivi des tâches",
    enable: "Activer le suivi des tâches",
    needsProperty:
      "Ajoutez une propriété active de statut ou de sélection avant d'activer le suivi.",
    invalid:
      "La configuration des rôles est invalide. Choisissez des propriétés actives et compatibles.",
    saving: "Enregistrement local des rôles…",
    status: "Propriété de statut de la tâche",
    dueDate: "Propriété d'échéance de la tâche",
    priority: "Propriété de priorité de la tâche",
  },
  table: {
    editCancelled: "Modification annulée",
    titleRequired: "Donnez un titre à la page.",
    saveFailed: "La valeur n'a pas pu être enregistrée.",
    editing: (property: string, title: string) => `Modification de ${property} pour ${title}`,
    saved: (property: string, title: string) => `${property} enregistré pour ${title}`,
    viewLabel: (name: string) => `Vue tableau ${name}`,
    scrollLabel: (name: string) => `Tableau défilant ${name}`,
    width: (property: string, pixels: number) => `Largeur de ${property} : ${pixels} pixels`,
    titleFor: (title: string) => `Titre de ${title}`,
    narrow: (property: string) => `Réduire la largeur de ${property}`,
    widen: (property: string) => `Augmenter la largeur de ${property}`,
    saving: (property: string) => `Enregistrement de ${property}…`,
    saveFor: (property: string, title: string) => `Enregistrer ${property} pour ${title}`,
    cancelEdit: "Annuler la modification",
    openEntry: "Ouvrir l'entrée complète",
  },
  conflict: {
    missingVersions: "Ce conflit n'identifie pas les deux versions. Rien n'a été supprimé.",
    missingEntry: "Ce conflit n'identifie pas l'entrée de base de données concernée",
    region: "Résoudre un conflit structuré de base de données",
    heading: "Résoudre le conflit de base de données",
    explanation:
      "Ces champs ont changé sur deux appareils. Comparez leur point de départ, puis choisissez chaque champ en conflit. Les modifications compatibles des deux appareils sont déjà conservées.",
    caption: "Structure, vue ou valeurs de propriété nécessitant votre choix.",
    field: "Champ",
    thisDevice: "Cet appareil",
    ancestor: "Ancêtre commun",
    otherDevice: "Autre appareil",
    keep: "Conserver",
    keepFor: (path: string) => `Valeur à conserver pour ${path}`,
    review: "Vérifier avant l'enregistrement",
    confirmSchema: "Confirmer la structure résolue",
    schemaImpact:
      "Cette résolution change la façon dont les valeurs enregistrées correspondent à la structure.",
    save: "Enregistrer cette résolution",
    removed: "(supprimé)",
  },
  hierarchy: {
    notAvailable: "La base de données n'est pas disponible",
    entryNotAvailable: "L'entrée de base de données n'est pas disponible localement",
    valuesNotAvailable: "Les valeurs de l'entrée ne sont pas disponibles localement",
    entryCellChanged: "Cette entrée a continué à changer pendant l'enregistrement de sa cellule",
    trashImpact: (name: string, count: number) =>
      `Placer « ${name} » et ${count} ${count === 1 ? "entrée active" : "entrées actives"} de la base de données dans la corbeille ?`,
    newInside: (name: string) => `Nouvelle base de données dans ${name}`,
    addInside: "+ base de données",
    newRoot: "Nouvelle base de données racine",
    schemaChanged: "La structure de la base a changé pendant la modification de cette propriété",
    viewChanged: "La vue a changé simultanément et nécessite une résolution",
    propertySaveChanged: "La base a continué à changer pendant l'enregistrement de cette propriété",
    entryChanged: "Cette entrée a changé pendant la modification de ses propriétés",
    entrySaveChanged:
      "Cette entrée a continué à changer pendant l'enregistrement de ses propriétés",
  },
} as const;

/** The active locale is owned by the application shell, not persisted data. */
export const DATABASE_LOCALE = "fr-FR";

/** Format an arbitrary-size canonical decimal without converting it to a JS number. */
export function formatDatabaseDecimal(canonical: string): string {
  const [integer = "0", fraction] = canonical.split(".");
  const formattedInteger = new Intl.NumberFormat(DATABASE_LOCALE, {
    maximumFractionDigits: 0,
    useGrouping: true,
  }).format(BigInt(integer));
  if (fraction === undefined) return formattedInteger;
  const decimal =
    new Intl.NumberFormat(DATABASE_LOCALE).formatToParts(1.1).find(({ type }) => type === "decimal")
      ?.value ?? ".";
  return `${formattedInteger}${decimal}${fraction}`;
}
