/**
 * English copy for the database feature.
 *
 * The application currently ships one active language. Keeping every 009
 * message behind this boundary lets the release-wide locale switch replace a
 * catalogue without coupling translated labels to canonical database data.
 */
export const DATABASE_COPY = {
  common: {
    cancel: "Cancel",
    close: "Close",
    conflict: "Conflict",
    remove: "Remove",
    savedLocally: "Saved locally",
    saving: "Saving…",
    savingLocally: "Saving locally…",
    unavailableOption: "Unavailable option",
    unavailableProperty: "Unavailable property",
    noUsableView: "This database has no usable view.",
    noEntriesAvailable: "No entries in the data available on this device.",
    noEntries: "No entries in this view.",
    noCardsAvailable: "No cards in the data available on this device.",
    noCards: "No cards in this view.",
    noValue: "No value",
    noPage: "No page",
    preserveIncompatible: "Preserve incompatible values",
    discardAffected: "Discard affected values",
  },
  create: {
    nameRequired: "Give the database a name.",
    failed: "The database could not be created. Your name is still here.",
    label: "Create a database",
    placeholder: "Projects, tasks, reading…",
    creating: "Creating…",
    submit: "Create database",
    initialViewName: "Table",
    initialTitlePropertyName: "Title",
  },
  page: {
    propertySaveFailed: "The property could not be saved. Your draft is still here.",
    titleRequired: "Give the page a title.",
    entryCreateFailed: "The entry could not be created. Your title is still here.",
    eyebrow: "Database · page",
    addProperty: "Add property",
    properties: "Properties",
    confirmSchemaChange: "Confirm schema change",
    schemaImpactHeading: "This schema change affects saved values",
    newEntry: "New entry",
    untitledPage: "Untitled page",
    loadingView: "Loading the saved view…",
    invalidView: "This view is invalid. Repair the highlighted rule.",
    rebuildingView: "The complete view is rebuilding. Safe local data remains visible.",
    staleView: "The view changed; the first page was reloaded.",
    impact: (valueCount: number, entryCount: number) =>
      `${valueCount} ${valueCount === 1 ? "value" : "values"} across ${entryCount} ${entryCount === 1 ? "entry" : "entries"}.`,
    completeResult: (count: number) => `Complete result · ${count} entries`,
    partialResult: (available: number, expected: number) =>
      `Local data partial: ${available} of ${expected}`,
  },
  toolbar: {
    viewName: "View name",
    renaming: "Renaming…",
    rename: "Rename view",
    savedViews: "Saved database views",
    views: "Views",
    viewTypes: {
      table: "table",
      list: "list",
      board: "board",
      gallery: "gallery",
      calendar: "calendar",
    },
    newTable: "New table view",
    newList: "New list view",
    newBoard: "New board view",
    newGallery: "New gallery view",
    newCalendar: "New calendar view",
    boardNeedsProperty: "Add a status or select property first",
    calendarNeedsProperty: "Add a date property first",
    duplicate: "Duplicate view",
    moveEarlier: "Move view earlier",
    moveLater: "Move view later",
    remove: "Remove view",
    needsOneView: "A database must keep one active view",
    visibleProperties: "Visible properties",
    defaultViewName: (type: "Table" | "List" | "Board" | "Gallery" | "Calendar", n: number) =>
      `${type} ${n}`,
    copyName: (name: string) => `${name} copy`,
    actionsFor: (name: string) => `Actions for ${name}`,
    moveColumnEarlier: (name: string) => `Move ${name} column earlier`,
    moveColumnLater: (name: string) => `Move ${name} column later`,
  },
  property: {
    nameRequired: "Give the property a name.",
    nameTooLong: "Property names must be 512 characters or fewer.",
    distinctOptions: "Each option needs a distinct label.",
    editor: "Property editor",
    name: "Name",
    type: "Type",
    typeLabels: {
      title: "title",
      text: "text",
      number: "number",
      date: "date",
      status: "status",
      select: "select",
      "multi-select": "multi-select",
      checkbox: "checkbox",
      relation: "relation",
    },
    optionPlaceholder: "Planned, In progress, Done",
    optionsSeparated: "Options, separated by commas",
    dateMode: "Date precision",
    calendarDate: "Calendar date",
    dateAndTime: "Date and time",
    relationCardinality: "Allowed targets",
    onePage: "One page",
    manyPages: "Many pages",
    save: "Save property",
  },
  value: {
    titleOnPage: "The title is edited as the page name.",
    chooseChecked: "Choose whether this is checked.",
    chooseOptions: "Choose one or more options.",
    staleOption: "One of these options is no longer available.",
    choosePage: "Choose an available page.",
    onePageOnly: "This relation accepts one page only.",
    enter: "Enter a value.",
    decimalDot: "Use a dot as the decimal separator.",
    decimalExample: "Enter a decimal number, for example 12.5.",
    realDate: "Enter a real date in YYYY-MM-DD format.",
    zonedDate: "Enter a date and time with a timezone offset.",
    chooseOption: "Choose an available option.",
    unavailableOption: "This option is no longer available.",
    unsupported: "This value type is not supported.",
    emptyText: "Empty text",
    yes: "Yes",
    no: "No",
    linked: (count: number) => `${count} linked`,
  },
  filter: {
    periodFor: (name: string) => `Period for ${name}`,
    from: "From",
    to: "To",
    fromFor: (name: string, timezone: string) => `From for ${name}${timezone}`,
    toFor: (name: string, timezone: string) => `To for ${name}${timezone}`,
    valueFor: (name: string) => `Value for ${name}`,
    chooseOption: "Choose an option",
    notChecked: "Not checked",
    checked: "Checked",
    pageIdentity: "Page identity",
    value: "Value",
    filters: "Filters",
    allRulesShort: "all rules",
    anyRuleShort: "any rule",
    match: "Match",
    combination: "Filter combination",
    allRules: "All rules",
    anyRules: "At least one rule",
    unavailable: "Unavailable property · repair or remove this filter",
    property: "Property",
    operator: "Operator",
    operatorLabels: {
      equals: "equals",
      "not-equals": "not equals",
      "is-empty": "is empty",
      "is-not-empty": "is not empty",
      contains: "contains",
      "not-contains": "not contains",
      before: "before",
      after: "after",
      between: "between",
      "less-than": "less than",
      "greater-than": "greater than",
    },
    removeRule: "Remove rule",
    add: "Add filter",
    clear: "Clear filters",
    saving: "Saving filters…",
    save: "Save filters",
  },
  sort: {
    heading: "Sort & group",
    grouped: "grouped",
    property: "Sort property",
    direction: "Direction",
    ascending: "Ascending",
    descending: "Descending",
    emptyValues: "Empty values",
    last: "Last",
    first: "First",
    remove: "Remove sort",
    moveEarlier: "Move sort earlier",
    moveLater: "Move sort later",
    add: "Add sort",
    groupBy: "Group by",
    noGrouping: "No grouping",
    saving: "Saving sort and group…",
    save: "Save sort and group",
    summary: (count: number, grouped: boolean) =>
      `Sort & group · ${count} ${count === 1 ? "sort" : "sorts"}${grouped ? " · grouped" : ""}`,
  },
  board: {
    noPropertyValue: (name: string) => `No ${name.toLocaleLowerCase(DATABASE_LOCALE)}`,
    cardsFor: (name: string) => `${name} cards`,
    moveToAnother: (title: string) => `Move ${title} to another column`,
    movePrevious: (title: string) => `Move ${title} to previous column`,
    moveNext: (title: string) => `Move ${title} to next column`,
    previous: "Previous column",
    next: "Next column",
    viewLabel: (name: string) => `${name} board view`,
    needsProperty: "Add an active status or select property to use this board.",
    moved: (title: string, column: string) => `${title} moved to ${column}`,
    moveFailed: (title: string) => `${title} could not be moved`,
    groupingProperty: "Board grouping property",
    columnsGroupedBy: (name: string) => `Columns grouped by ${name}`,
    expand: "Expand",
    collapse: "Collapse",
    noCards: "No cards",
  },
  calendar: {
    viewLabel: (name: string) => `${name} calendar view`,
    needsProperty: "Add an active date property to use this calendar.",
    scheduled: (title: string, date: string) => `${title} scheduled for ${date}`,
    scheduleFailed: (title: string) => `${title} could not be scheduled`,
    schedule: (title: string) => `Schedule ${title}`,
    movePrevious: (title: string) => `Move ${title} to previous day`,
    moveNext: (title: string) => `Move ${title} to next day`,
    previousDay: "Previous day",
    nextDay: "Next day",
    dateProperty: "Calendar date property",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    unscheduled: "Unscheduled",
    allScheduled: "Every visible entry is scheduled.",
  },
  gallery: {
    previewDisabled: "Preview disabled",
    noSafePreview: "No safe preview available",
    viewLabel: (name: string) => `${name} gallery view`,
    settings: "Gallery card settings",
    preview: "Card preview",
    none: "No preview",
    page: "Page content",
    file: "First available safe file",
    properties: "Properties shown on cards",
  },
  list: {
    viewLabel: (name: string) => `${name} list view`,
  },
  entry: {
    saved: "Properties saved locally.",
    saveFailed: "The properties could not be saved. Your values are still here.",
    eyebrow: "Database entry · page",
    close: "Close entry",
    noProperties: "This database has no additional properties yet.",
    taskTracking: "Task tracking",
    taskStatus: "Task status",
    taskDueDate: "Task due date",
    taskPriority: "Task priority",
    otherProperties: "Other properties",
    save: "Save properties",
    pageContent: "Page content",
    samePageDocument: "The editorial document belongs to this same page.",
  },
  task: {
    notConfigured: "Not configured",
    saveFailed: "Task roles could not be saved. The previous configuration was restored.",
    tracking: "Task tracking",
    explanation:
      "Task roles reference existing properties. Entries remain ordinary editable pages.",
    disable: "Disable task tracking",
    enable: "Enable task tracking",
    needsProperty: "Add an active status or select property before enabling task tracking.",
    invalid: "Task role configuration is invalid. Choose active compatible properties.",
    saving: "Saving task roles locally…",
    status: "Task status property",
    dueDate: "Task due date property",
    priority: "Task priority property",
  },
  table: {
    editCancelled: "Edit cancelled",
    titleRequired: "Give the page a title.",
    saveFailed: "The value could not be saved.",
    editing: (property: string, title: string) => `Editing ${property} for ${title}`,
    saved: (property: string, title: string) => `${property} saved for ${title}`,
    viewLabel: (name: string) => `${name} table view`,
    scrollLabel: (name: string) => `${name} scrollable table`,
    width: (property: string, pixels: number) => `${property} width ${pixels} pixels`,
    titleFor: (title: string) => `Title for ${title}`,
    narrow: (property: string) => `Narrow ${property}`,
    widen: (property: string) => `Widen ${property}`,
    saving: (property: string) => `Saving ${property}…`,
    saveFor: (property: string, title: string) => `Save ${property} for ${title}`,
    cancelEdit: "Cancel edit",
    openEntry: "Open full entry",
  },
  conflict: {
    missingVersions: "This conflict does not identify both versions. Nothing has been discarded.",
    missingEntry: "This conflict does not identify its database entry",
    region: "Resolve structured database conflict",
    heading: "Resolve database conflict",
    explanation:
      "These fields changed on two devices. Compare what both devices started from, then choose each conflicting field. Compatible changes from both devices are already kept.",
    caption: "Schema, view, or property values requiring your choice.",
    field: "Field",
    thisDevice: "This device",
    ancestor: "Common ancestor",
    otherDevice: "Other device",
    keep: "Keep",
    keepFor: (path: string) => `Keep for ${path}`,
    review: "Review before saving",
    confirmSchema: "Confirm resolved schema",
    schemaImpact: "This resolution changes how saved values fit the schema.",
    save: "Save this resolution",
    removed: "(removed)",
  },
  hierarchy: {
    notAvailable: "Database is not available",
    entryNotAvailable: "Database entry is not available locally",
    valuesNotAvailable: "Database entry values are not available locally",
    entryCellChanged: "This entry kept changing while its cell was being saved",
    trashImpact: (name: string, count: number) =>
      `Move “${name}” and ${count} active database ${count === 1 ? "entry" : "entries"} to the trash?`,
    newInside: (name: string) => `New database inside ${name}`,
    addInside: "+database",
    newRoot: "New root database",
    schemaChanged: "The database schema changed while this property was being edited",
    viewChanged: "The database view changed concurrently and needs resolution",
    propertySaveChanged: "The database kept changing while this property was being saved",
    entryChanged: "This entry changed while its properties were being edited",
    entrySaveChanged: "This entry kept changing while its properties were being saved",
  },
} as const;

/** The active locale is owned by the application shell, not persisted data. */
export const DATABASE_LOCALE = "en";

/** Format an arbitrary-size canonical decimal without converting it to a JS number. */
export function formatDatabaseDecimal(canonical: string): string {
  const [integer = "0", fraction] = canonical.split(".");
  const formattedInteger = new Intl.NumberFormat(DATABASE_LOCALE, {
    maximumFractionDigits: 0,
    useGrouping: true,
  }).format(BigInt(integer));
  if (fraction === undefined) return formattedInteger;
  const decimal =
    new Intl.NumberFormat(DATABASE_LOCALE).formatToParts(1.1).find(({ type }) => type === "decimal")
      ?.value ?? ".";
  return `${formattedInteger}${decimal}${fraction}`;
}
