import {
  Accessibility,
  Activity,
  AlarmClock,
  Anchor,
  Apple,
  Archive,
  AtSign,
  Award,
  Axe,
  Baby,
  Backpack,
  Badge,
  Ban,
  Banana,
  Banknote,
  Bath,
  Battery,
  Bed,
  Beef,
  Beer,
  Bell,
  BellOff,
  Bike,
  Binoculars,
  Bird,
  Bluetooth,
  Bomb,
  Bone,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Castle,
  Cat,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CheckCheck,
  Cherry,
  Church,
  Circle,
  CircleCheck,
  Clapperboard,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  CloudSun,
  Clover,
  Coffee,
  Coins,
  Compass,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dice5,
  Dog,
  DoorOpen,
  Droplet,
  Drum,
  Dumbbell,
  Egg,
  Eraser,
  Eye,
  Factory,
  Feather,
  File,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Folder,
  FolderKanban,
  FolderOpen,
  Footprints,
  Frown,
  Fuel,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grape,
  Guitar,
  Hammer,
  Hand,
  Hash,
  Headphones,
  Heart,
  HeartHandshake,
  Hexagon,
  Highlighter,
  Home,
  Hospital,
  Hourglass,
  IceCreamCone,
  Inbox,
  Info,
  Key,
  Lamp,
  Landmark,
  Laugh,
  Leaf,
  Library,
  Lightbulb,
  Link,
  List,
  ListTodo,
  Lock,
  LockOpen,
  type LucideIcon,
  Luggage,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Meh,
  MessageCircle,
  MessageSquare,
  Mic,
  Moon,
  Mountain,
  Music,
  Music2,
  Navigation,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  Paintbrush,
  Palette,
  Paperclip,
  PawPrint,
  Pen,
  Pencil,
  PenTool,
  Phone,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Presentation,
  Printer,
  Puzzle,
  Quote,
  Rabbit,
  Radio,
  Receipt,
  Rocket,
  Ruler,
  Sandwich,
  School,
  Scissors,
  Scroll,
  Send,
  Server,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Signpost,
  Skull,
  Smile,
  SmilePlus,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Sprout,
  Square,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Sword,
  Syringe,
  Tag,
  Tags,
  Target,
  Tent,
  ThumbsDown,
  ThumbsUp,
  TrainFront,
  TreeDeciduous,
  TreePine,
  Triangle,
  TriangleAlert,
  Trophy,
  Truck,
  Turtle,
  Umbrella,
  User,
  Users,
  Utensils,
  Video,
  Volleyball,
  Wallet,
  Warehouse,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export interface SymbolIconChoice {
  readonly id: string;
  readonly label: string;
  readonly Icon: LucideIcon;
}

const CHOICES: readonly SymbolIconChoice[] = [
  { id: "accessibility", label: "accessibilité", Icon: Accessibility },
  { id: "activity", label: "activité", Icon: Activity },
  { id: "alarm-clock", label: "réveil", Icon: AlarmClock },
  { id: "anchor", label: "ancre", Icon: Anchor },
  { id: "apple", label: "pomme", Icon: Apple },
  { id: "archive", label: "archive", Icon: Archive },
  { id: "at-sign", label: "arobase", Icon: AtSign },
  { id: "award", label: "récompense", Icon: Award },
  { id: "axe", label: "hache", Icon: Axe },
  { id: "baby", label: "bébé", Icon: Baby },
  { id: "backpack", label: "sac", Icon: Backpack },
  { id: "badge", label: "badge", Icon: Badge },
  { id: "banana", label: "banane", Icon: Banana },
  { id: "ban", label: "interdit", Icon: Ban },
  { id: "banknote", label: "billet", Icon: Banknote },
  { id: "bath", label: "bain", Icon: Bath },
  { id: "battery", label: "batterie", Icon: Battery },
  { id: "bed", label: "lit", Icon: Bed },
  { id: "beef", label: "viande", Icon: Beef },
  { id: "beer", label: "bière", Icon: Beer },
  { id: "bell", label: "cloche", Icon: Bell },
  { id: "bell-off", label: "cloche barrée", Icon: BellOff },
  { id: "bike", label: "vélo", Icon: Bike },
  { id: "binoculars", label: "jumelles", Icon: Binoculars },
  { id: "bird", label: "oiseau", Icon: Bird },
  { id: "bluetooth", label: "bluetooth", Icon: Bluetooth },
  { id: "bomb", label: "bombe", Icon: Bomb },
  { id: "bone", label: "os", Icon: Bone },
  { id: "book", label: "livre", Icon: Book },
  { id: "book-open", label: "livre ouvert", Icon: BookOpen },
  { id: "bookmark", label: "signet", Icon: Bookmark },
  { id: "bot", label: "robot", Icon: Bot },
  { id: "box", label: "boîte", Icon: Box },
  { id: "boxes", label: "cartons", Icon: Boxes },
  { id: "brain", label: "cerveau", Icon: Brain },
  { id: "briefcase", label: "mallette", Icon: Briefcase },
  { id: "bug", label: "insecte", Icon: Bug },
  { id: "building", label: "immeuble", Icon: Building },
  { id: "building-2", label: "bureau", Icon: Building2 },
  { id: "bus", label: "bus", Icon: Bus },
  { id: "cake", label: "gâteau", Icon: Cake },
  { id: "calculator", label: "calculatrice", Icon: Calculator },
  { id: "calendar", label: "calendrier", Icon: Calendar },
  { id: "calendar-days", label: "agenda", Icon: CalendarDays },
  { id: "camera", label: "appareil photo", Icon: Camera },
  { id: "car", label: "voiture", Icon: Car },
  { id: "castle", label: "château", Icon: Castle },
  { id: "cat", label: "chat", Icon: Cat },
  { id: "chart-bar", label: "barres", Icon: ChartBar },
  { id: "chart-line", label: "courbe", Icon: ChartLine },
  { id: "chart-pie", label: "camembert", Icon: ChartPie },
  { id: "check", label: "coche", Icon: Check },
  { id: "check-check", label: "double coche", Icon: CheckCheck },
  { id: "check-circle", label: "validé", Icon: CircleCheck },
  { id: "cherry", label: "cerise", Icon: Cherry },
  { id: "church", label: "église", Icon: Church },
  { id: "circle", label: "cercle", Icon: Circle },
  { id: "clapperboard", label: "clap", Icon: Clapperboard },
  { id: "clipboard", label: "presse-papiers", Icon: Clipboard },
  { id: "clipboard-list", label: "liste cochée", Icon: ClipboardList },
  { id: "clock", label: "horloge", Icon: Clock },
  { id: "cloud", label: "nuage", Icon: Cloud },
  { id: "cloud-rain", label: "pluie", Icon: CloudRain },
  { id: "cloud-sun", label: "éclaircie", Icon: CloudSun },
  { id: "clover", label: "trèfle", Icon: Clover },
  { id: "coffee", label: "café", Icon: Coffee },
  { id: "coins", label: "pièces", Icon: Coins },
  { id: "compass", label: "boussole", Icon: Compass },
  { id: "cookie", label: "biscuit", Icon: Cookie },
  { id: "cpu", label: "processeur", Icon: Cpu },
  { id: "credit-card", label: "carte bancaire", Icon: CreditCard },
  { id: "croissant", label: "croissant", Icon: Croissant },
  { id: "crown", label: "couronne", Icon: Crown },
  { id: "cup-soda", label: "soda", Icon: CupSoda },
  { id: "database", label: "base", Icon: Database },
  { id: "diamond", label: "diamant", Icon: Diamond },
  { id: "dice", label: "dé", Icon: Dice5 },
  { id: "dog", label: "chien", Icon: Dog },
  { id: "door-open", label: "porte", Icon: DoorOpen },
  { id: "droplet", label: "goutte", Icon: Droplet },
  { id: "drum", label: "tambour", Icon: Drum },
  { id: "dumbbell", label: "haltère", Icon: Dumbbell },
  { id: "egg", label: "œuf", Icon: Egg },
  { id: "eraser", label: "gomme", Icon: Eraser },
  { id: "eye", label: "œil", Icon: Eye },
  { id: "factory", label: "usine", Icon: Factory },
  { id: "feather", label: "plume", Icon: Feather },
  { id: "file", label: "fichier", Icon: File },
  { id: "file-text", label: "document", Icon: FileText },
  { id: "film", label: "film", Icon: Film },
  { id: "fish", label: "poisson", Icon: Fish },
  { id: "flag", label: "drapeau", Icon: Flag },
  { id: "flame", label: "flamme", Icon: Flame },
  { id: "flower", label: "fleur", Icon: Flower2 },
  { id: "folder", label: "dossier", Icon: Folder },
  { id: "folder-kanban", label: "kanban", Icon: FolderKanban },
  { id: "folder-open", label: "dossier ouvert", Icon: FolderOpen },
  { id: "footprints", label: "empreintes", Icon: Footprints },
  { id: "frown", label: "triste", Icon: Frown },
  { id: "fuel", label: "essence", Icon: Fuel },
  { id: "gamepad", label: "manette", Icon: Gamepad2 },
  { id: "gem", label: "pierre", Icon: Gem },
  { id: "ghost", label: "fantôme", Icon: Ghost },
  { id: "gift", label: "cadeau", Icon: Gift },
  { id: "glasses", label: "lunettes", Icon: Glasses },
  { id: "globe", label: "globe", Icon: Globe },
  { id: "graduation-cap", label: "diplôme", Icon: GraduationCap },
  { id: "grape", label: "raisin", Icon: Grape },
  { id: "guitar", label: "guitare", Icon: Guitar },
  { id: "hammer", label: "marteau", Icon: Hammer },
  { id: "hand", label: "main", Icon: Hand },
  { id: "hash", label: "dièse", Icon: Hash },
  { id: "headphones", label: "casque", Icon: Headphones },
  { id: "heart", label: "cœur", Icon: Heart },
  { id: "heart-handshake", label: "entraide", Icon: HeartHandshake },
  { id: "hexagon", label: "hexagone", Icon: Hexagon },
  { id: "highlighter", label: "surligneur", Icon: Highlighter },
  { id: "home", label: "maison", Icon: Home },
  { id: "hospital", label: "hôpital", Icon: Hospital },
  { id: "hourglass", label: "sablier", Icon: Hourglass },
  { id: "ice-cream", label: "glace", Icon: IceCreamCone },
  { id: "inbox", label: "réception", Icon: Inbox },
  { id: "info", label: "information", Icon: Info },
  { id: "key", label: "clé", Icon: Key },
  { id: "lamp", label: "lampe", Icon: Lamp },
  { id: "landmark", label: "monument", Icon: Landmark },
  { id: "laugh", label: "rire", Icon: Laugh },
  { id: "leaf", label: "feuille", Icon: Leaf },
  { id: "library", label: "bibliothèque", Icon: Library },
  { id: "lightbulb", label: "ampoule", Icon: Lightbulb },
  { id: "link", label: "lien", Icon: Link },
  { id: "list", label: "liste", Icon: List },
  { id: "list-todo", label: "tâches", Icon: ListTodo },
  { id: "lock", label: "cadenas", Icon: Lock },
  { id: "lock-open", label: "cadenas ouvert", Icon: LockOpen },
  { id: "luggage", label: "valise", Icon: Luggage },
  { id: "magnet", label: "aimant", Icon: Magnet },
  { id: "mail", label: "courrier", Icon: Mail },
  { id: "map", label: "carte", Icon: MapIcon },
  { id: "map-pin", label: "lieu", Icon: MapPin },
  { id: "medal", label: "médaille", Icon: Medal },
  { id: "meh", label: "neutre", Icon: Meh },
  { id: "message", label: "message", Icon: MessageCircle },
  { id: "message-square", label: "discussion", Icon: MessageSquare },
  { id: "mic", label: "micro", Icon: Mic },
  { id: "moon", label: "lune", Icon: Moon },
  { id: "mountain", label: "montagne", Icon: Mountain },
  { id: "music", label: "musique", Icon: Music },
  { id: "music-note", label: "note", Icon: Music2 },
  { id: "navigation", label: "boussole active", Icon: Navigation },
  { id: "newspaper", label: "journal", Icon: Newspaper },
  { id: "notebook", label: "carnet", Icon: Notebook },
  { id: "notebook-pen", label: "notes", Icon: NotebookPen },
  { id: "package", label: "colis", Icon: Package },
  { id: "paintbrush", label: "pinceau", Icon: Paintbrush },
  { id: "palette", label: "palette", Icon: Palette },
  { id: "paperclip", label: "trombone", Icon: Paperclip },
  { id: "paw", label: "patte", Icon: PawPrint },
  { id: "pen", label: "stylo", Icon: Pen },
  { id: "pencil", label: "crayon", Icon: Pencil },
  { id: "pen-tool", label: "stylet", Icon: PenTool },
  { id: "phone", label: "téléphone", Icon: Phone },
  { id: "piggy-bank", label: "tirelire", Icon: PiggyBank },
  { id: "pill", label: "comprimé", Icon: Pill },
  { id: "pin", label: "épingle", Icon: Pin },
  { id: "pizza", label: "pizza", Icon: Pizza },
  { id: "plane", label: "avion", Icon: Plane },
  { id: "plug", label: "prise", Icon: Plug },
  { id: "popcorn", label: "pop-corn", Icon: Popcorn },
  { id: "presentation", label: "présentation", Icon: Presentation },
  { id: "printer", label: "imprimante", Icon: Printer },
  { id: "puzzle", label: "puzzle", Icon: Puzzle },
  { id: "quote", label: "citation", Icon: Quote },
  { id: "rabbit", label: "lapin", Icon: Rabbit },
  { id: "radio", label: "radio", Icon: Radio },
  { id: "receipt", label: "reçu", Icon: Receipt },
  { id: "rocket", label: "fusée", Icon: Rocket },
  { id: "ruler", label: "règle", Icon: Ruler },
  { id: "sandwich", label: "sandwich", Icon: Sandwich },
  { id: "school", label: "école", Icon: School },
  { id: "scissors", label: "ciseaux", Icon: Scissors },
  { id: "scroll", label: "parchemin", Icon: Scroll },
  { id: "send", label: "envoi", Icon: Send },
  { id: "server", label: "serveur", Icon: Server },
  { id: "shield", label: "bouclier", Icon: Shield },
  { id: "ship", label: "bateau", Icon: Ship },
  { id: "shirt", label: "chemise", Icon: Shirt },
  { id: "shopping-bag", label: "cabas", Icon: ShoppingBag },
  { id: "shopping-cart", label: "panier", Icon: ShoppingCart },
  { id: "signpost", label: "panneau", Icon: Signpost },
  { id: "skull", label: "crâne", Icon: Skull },
  { id: "smile", label: "sourire", Icon: Smile },
  { id: "smile-plus", label: "sourire large", Icon: SmilePlus },
  { id: "snowflake", label: "flocon", Icon: Snowflake },
  { id: "sofa", label: "canapé", Icon: Sofa },
  { id: "soup", label: "soupe", Icon: Soup },
  { id: "sparkles", label: "étincelles", Icon: Sparkles },
  { id: "sprout", label: "pousse", Icon: Sprout },
  { id: "square", label: "carré", Icon: Square },
  { id: "star", label: "étoile", Icon: Star },
  { id: "stethoscope", label: "stéthoscope", Icon: Stethoscope },
  { id: "sticky-note", label: "pense-bête", Icon: StickyNote },
  { id: "store", label: "boutique", Icon: Store },
  { id: "sun", label: "soleil", Icon: Sun },
  { id: "sword", label: "épée", Icon: Sword },
  { id: "syringe", label: "seringue", Icon: Syringe },
  { id: "tag", label: "étiquette", Icon: Tag },
  { id: "tags", label: "étiquettes", Icon: Tags },
  { id: "target", label: "cible", Icon: Target },
  { id: "tent", label: "tente", Icon: Tent },
  { id: "thumbs-down", label: "pouce baissé", Icon: ThumbsDown },
  { id: "thumbs-up", label: "pouce", Icon: ThumbsUp },
  { id: "train", label: "train", Icon: TrainFront },
  { id: "tree", label: "sapin", Icon: TreePine },
  { id: "tree-deciduous", label: "arbre", Icon: TreeDeciduous },
  { id: "triangle", label: "triangle", Icon: Triangle },
  { id: "triangle-alert", label: "alerte", Icon: TriangleAlert },
  { id: "trophy", label: "trophée", Icon: Trophy },
  { id: "truck", label: "camion", Icon: Truck },
  { id: "turtle", label: "tortue", Icon: Turtle },
  { id: "umbrella", label: "parapluie", Icon: Umbrella },
  { id: "user", label: "personne", Icon: User },
  { id: "users", label: "personnes", Icon: Users },
  { id: "utensils", label: "couverts", Icon: Utensils },
  { id: "video", label: "vidéo", Icon: Video },
  { id: "volleyball", label: "volley", Icon: Volleyball },
  { id: "wallet", label: "portefeuille", Icon: Wallet },
  { id: "warehouse", label: "entrepôt", Icon: Warehouse },
  { id: "watch", label: "montre", Icon: Watch },
  { id: "waves", label: "vagues", Icon: Waves },
  { id: "wifi", label: "wifi", Icon: Wifi },
  { id: "wind", label: "vent", Icon: Wind },
  { id: "wine", label: "vin", Icon: Wine },
  { id: "wrench", label: "clé à molette", Icon: Wrench },
  { id: "zap", label: "éclair", Icon: Zap },
];

const BY_ID = new Map(CHOICES.map((choice) => [choice.id, choice]));

/** Page icons store this prefix so a symbol id never collides with an emoji. */
export const PAGE_SYMBOL_PREFIX = "symbol:";

export const SYMBOL_ICON_CHOICES = CHOICES;

export function symbolIconChoice(value: string | null | undefined): SymbolIconChoice | null {
  if (value == null || value === "") return null;
  const id = value.startsWith(PAGE_SYMBOL_PREFIX) ? value.slice(PAGE_SYMBOL_PREFIX.length) : value;
  return BY_ID.get(id) ?? null;
}

export function pageSymbolIcon(id: string): string {
  return `${PAGE_SYMBOL_PREFIX}${id}`;
}
