/**
 * A directory on disk, implementing the destination boundary in full.
 *
 * Not a test double. This is a destination an owner can legitimately choose — a
 * mounted network share, an external disk — and it is also what every test uses,
 * which is the point: the implementation that proves the feature works is one
 * that does the same work as the real one, rather than a stub that agrees with
 * whatever the tests expect.
 *
 * It stores the ciphertext it is given and nothing else. No manifest is written
 * beside it, however convenient that would be for listing backups, because a
 * manifest describes somebody's workspace.
 */

import { createReadStream, createWriteStream } from "node:fs";
import { mkdir, readdir, rm, stat } from "node:fs/promises";
import path from "node:path";
import type { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import {
  type BackupDestination,
  DestinationUnavailableError,
  type StoredBackup,
} from "./destination.ts";

export class FilesystemDestination implements BackupDestination {
  readonly name = "filesystem";

  constructor(private readonly root: string) {}

  /**
   * Refuses a name that could escape the root.
   *
   * Names are generated by this application, so this can never fire today. It is
   * here because a destination is exactly the surface where a path from a
   * manifest — that is, from an archive somebody handed over — could one day be
   * used, and a traversal there writes wherever the server can write.
   */
  #resolve(name: string): string {
    if (name.includes("/") || name.includes("\\") || name === "." || name === "..") {
      throw new DestinationUnavailableError(this.name, "a backup name must not contain a path");
    }
    return path.join(this.root, name);
  }

  async put(name: string, contents: Readable, _byteLength: number): Promise<void> {
    await mkdir(this.root, { recursive: true });
    const target = this.#resolve(name);
    // Written beside its final name and moved into place would be better still;
    // a partial file here is removed instead, because a half-written archive
    // that keeps its name looks like a smaller backup rather than a broken one.
    try {
      await pipeline(contents, createWriteStream(target));
    } catch (error) {
      await rm(target, { force: true });
      throw error;
    }
  }

  async list(): Promise<StoredBackup[]> {
    let names: string[];
    try {
      names = await readdir(this.root);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        // Nothing stored yet is not a failure: it is what a new installation
        // looks like on its first evening.
        return [];
      }
      throw new DestinationUnavailableError(this.name, (error as Error).message);
    }
    const stored: StoredBackup[] = [];
    for (const name of names) {
      const info = await stat(path.join(this.root, name));
      if (info.isFile()) {
        stored.push({ name, byteLength: info.size, storedAt: info.mtime });
      }
    }
    return stored.sort((left, right) => left.name.localeCompare(right.name));
  }

  async read(name: string): Promise<Readable | null> {
    const target = this.#resolve(name);
    try {
      await stat(target);
    } catch {
      return null;
    }
    return createReadStream(target);
  }

  async delete(name: string): Promise<void> {
    await rm(this.#resolve(name), { force: true });
  }
}
